# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2022-02-28 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asigm_1_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mobile_number',
        ),
    ]
