# Generated by Django 4.0.3 on 2022-03-26 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
